const form_data_defaults = {
    timestamp: '',
    status: 'PENDING',
    fName: '',
    middleInitial: '',
    lName: '',
    gender: '',
    age: '',
    address: {
        street1: '',
        street2: '',
        city: '',
        state: '',
        zip: ''
    },
    phone: '',
    otherLastNames: [],
    idSource: {
        driverLicenseOrId: '',
        expDate: '',
        lastFourSSN: '',
    },
    socialSecLastFour: '',
    situationReport: '',
    futurePlans: '',
    homeless: false,
    disabled: false,
    helpRequested: {
        rent: false,
        gasoline: false,
        licensePlate: '',
        busTicket: false,
        food: false,
    },
    lastHelpDate: '',
    landLord: {
        name: '',
        phone: '',
        verified: false,
        landLordAddress: {
            street1: '',
            street2: '',
            city: '',
            zip: ''
        },
    },
    childrenUnder18:  {
        hasChildrenUnder18: false,
        boysCount: 0,
        boysAges: [],
        girlsCount: 0,
        girlsAges: [],
        relationshipToChildren: '',
        schoolDistrict: '',
        schools: [],
    },
    otherAdults: [],
    monthlyHouseholdIncome: 0,
    monthlyIncomeLast12Months: 0,
    numberOfHouseholdMembersSupported: 0,
    singleMaleHeadOfHousehold: false,
    singleFemaleHeadOfHousehold: false,
    race: {
        americanIndianOrAlaskaNative: 0,
        whiteOrCaucasian: 0,
        asianAsianAmerican: 0,
        otherRace: 0,
        blackAfricanAmerican: 0,
        multiRacial: 0,
        latinoAmericanHispanic: 0,
        unknown: 0,
        nativeAmericanPacificIslander: 0,
    },
    referredBy: ''
}

export default form_data_defaults;